# Generated by Django 4.2.26 on 2025-11-16 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("instruction_text", models.TextField()),
                (
                    "rule_operator",
                    models.CharField(
                        choices=[
                            ("LESS_THAN", "Less Than"),
                            ("GREATER_THAN", "Greater Than"),
                            ("BETWEEN", "Between"),
                        ],
                        default="BETWEEN",
                        max_length=20,
                    ),
                ),
                (
                    "rule_value_a",
                    models.FloatField(
                        help_text="For BETWEEN: minimum value. For LESS_THAN: maximum value. For GREATER_THAN: minimum value."
                    ),
                ),
                (
                    "rule_value_b",
                    models.FloatField(
                        blank=True,
                        help_text="Only used for BETWEEN operator (maximum value).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InitialDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("initial_x", models.FloatField(help_text="Number of Stations")),
                ("initial_y", models.FloatField(help_text="Total System Length (km)")),
                (
                    "initial_z",
                    models.FloatField(
                        help_text="Ridership (billions, for bubble size)"
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_data",
                        to="range_tutor.challenge",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
